.PHONY : clean musicmeshfsd musicmeshfsc

all: musicmeshfsd musicmeshfsc

musicmeshfsd:
	$(MAKE) -C musicmeshfsd

musicmeshfsc:
	$(MAKE) -C musicmeshfsc

clean:
	$(MAKE) -C musicmeshfsd clean
	$(MAKE) -C musicmeshfsc clean
